-- OBSOLETE: This migration is NOT needed.
--
-- The Supabase database already has a function called `validate_kid_access_code`
-- (created by the web repo migration). That function serves the same purpose:
-- it validates kid access codes via SECURITY DEFINER to bypass RLS.
--
-- The mobile app now calls `validate_kid_access_code` directly (not `validate_kid_code`).
-- Do NOT run this migration — it would create a duplicate function with a different name.
--
-- If the function ever needs to be recreated, use the name `validate_kid_access_code`
-- to match both the web and mobile codebases.
